name: CMake on Windows-64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
      env:
        VCPKG_DEFAULT_TRIPLET: x64-windows

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |
        cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build --parallel

    - name: Publish Release
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir ${{github.workspace}}/release
        xcopy ${{github.workspace}}/build\Release\* ${{github.workspace}}/release /s /e /y

    - name: Upload Release
      uses: actions/upload-artifact@v3
      with:
        name: beatograph-win64
        path: ${{github.workspace}}/release
